version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 9005:9005
      - 3000:3000
    user: $USER
    command: >
      bash -c "npm install && npm run start"
    stdin_open: true
    tty: true
