# Generated by Django 3.1.6 on 2021-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
